import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://10.44.13.98/index.html');
  await page.getByRole('menuitem', { name: 'Jobs' }).click();
  await page.locator('#menu-jobs-jobQueue').getByRole('navigation', { name: 'Job Queue' }).click();
  await page.getByRole('textbox', { name: 'Enter PIN' }).fill('12345678');
  await page.getByRole('textbox', { name: 'Enter PIN' }).press('Enter');
  await expect(page.getByRole('button', { name: 'In progress' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Upcoming' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'History' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Job Name' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Status' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Started' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Completed' }).nth(1)).toBeVisible();
  await expect(page.getByRole('cell', { name: 'User Name' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Job Type' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Paper Source' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Paper Type' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Output Size' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Quality' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Color Mode' })).toBeVisible();
  await page.getByRole('button', { name: 'More actions' }).click();
  await expect(page.locator('div').filter({ hasText: /^Delete All Jobs in History$/ }).first()).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Cancel All Jobs$/ }).nth(2)).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Export History$/ }).first()).toBeVisible();
  await page.locator('div').filter({ hasText: /^Cancel All Jobs$/ }).first().click();
  await expect(page.getByRole('button', { name: 'No' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Yes' })).toBeVisible();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'More actions' }).click();
  await page.locator('div').filter({ hasText: /^Delete All Jobs in History$/ }).first().click();
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continue' })).toBeVisible();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('#menu-jobs-jobsAppSettings').getByRole('navigation', { name: 'Jobs Settings' }).click();
  await expect(page.getByText('Hide Deleted Jobs')).toBeVisible();
  await expect(page.getByText('Reprint from Job History')).toBeVisible();
  await expect(page.locator('.mat-slide-toggle-bar').first()).toBeVisible();
  await expect(page.locator('#reprintResendJobsEnabled > .mat-slide-toggle-label > .mat-slide-toggle-bar')).toBeVisible();
});